# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: svn2git 2.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "svn2git"
  s.version = "2.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["James Coglan", "Kevin Menard"]
  s.date = "2014-03-09"
  s.email = "nirvdrum@gmail.com"
  s.executables = ["svn2git"]
  s.extra_rdoc_files = [
    "ChangeLog.markdown",
    "README.markdown"
  ]
  s.files = [
    "ChangeLog.markdown",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "bin/svn2git",
    "lib/svn2git.rb",
    "lib/svn2git/blah.rb",
    "lib/svn2git/migration.rb",
    "svn2git.gemspec"
  ]
  s.homepage = "https://www.negativetwenty.net/redmine/projects/svn2git"
  s.rubygems_version = "2.2.0"
  s.summary = "A tool for migrating svn projects to git"
end

